### ISSUE TITLE
Slim the RFC by always requiring condition.

### ISSUE THREAD

**Issue by Danack** [iluuu1994/match-expression-rfc#3]
i.e. the bit

> It has been suggested to make no condition equivalent to (true).

Although that's a nice to have, it's a distraction for the core of the RFC imo. I would submit this as PR on the text......if that was in master.

**Comment by iluuu1994** [comment]
Makes sense to me. Might feel a little weird now that the majority voted for it, don't you think?

**Comment by Danack** [comment]
Gives them something to discuss: https://dilbert.com/strip/1997-07-12  ....

I don't think it makes a big dfiference, but was a small detail that one person didn't like.

**Comment by iluuu1994** [comment]
Done in https://github.com/iluuu1994/match-expression-rfc/pull/8
