### ISSUE TITLE
Remove history discussion

### ISSUE THREAD

**Issue by Danack** [iluuu1994/match-expression-rfc#4]
> Originally this RFC included a way to return a

RFC docs should be clear as possible to read _now_ - the meta level discussion about previous versions is a distraction that doesn't need to be there. Again, will submit PR when text is in master.

**Comment by iluuu1994** [comment]
Makes sense. 👍

**Comment by iluuu1994** [comment]
Done in https://github.com/iluuu1994/match-expression-rfc/pull/8
