### ISSUE TITLE
Fall through capabilties

### ISSUE THREAD

**Issue by Danack** [iluuu1994/match-expression-rfc#5]
I'm not sure exactly what is the right thing to do, but I think the RFC is weak on the fall-through capability and the text/idea needs to be improved.

```
match ($x) {
    $age >= 30 && $foo < 30,
    $age >= 20 && $foo < 20,
    $age >= 10 && $foo < 10 => {}
    default => {},
}
```

At least in part it's just the too many years I've been using switch with colons that makes the following be way more readable to me.

```
match ($x) {
    $age >= 30 && $foo < 30:
    $age >= 20 && $foo < 20:
    $age >= 10 && $foo < 10: {}
    default: {},
}
```

I can't justify that as actually better, it's just what I'm more used to.

**Comment by iluuu1994** [comment]
In your example you still need a way to tell PHP whether you want to jump to the next block or not.

```php
match (true) {
    $age >= 30 && $foo < 30: {
        // Matched, what now?
    }
    $age >= 20 && $foo < 20:
    $age >= 10 && $foo < 10: {}
    default: {},
}
```

So you'd still need a `fallthrough` keyword.

**Comment by iluuu1994** [comment]
I decided to remove blocks and propose them in a separate RFC. At this point fallthrough doesn't make sense (since the match arm body can only be a single expression). We'll re-evaluate this in the block RFC.
