### ISSUE TITLE
Actual real world example.

### ISSUE THREAD

**Issue by Danack** [iluuu1994/match-expression-rfc#6]
The RFC has no actual real working code in it. Having a real world example would make the conversation be a bit less abstract.

The context is I wanted to suggest a clarification on syntax, and went to copy the most believable example in the RFC to modify it.....and couldn't because there isn't one.

**Comment by iluuu1994** [comment]
Agreed, one of the biggest weak points of the RFC. I think many people are still confused on when a `match` statement/expression should be used.

**Comment by iluuu1994** [comment]
The RFC now contains a real-world example from Doctrine. I also tried to make the other examples more realistic. Let me know what you think.
