### ISSUE TITLE
wibbling about functionality.

### ISSUE THREAD

**Issue by Danack** [iluuu1994/match-expression-rfc#7]
This is a 'list' in php:

```
$labelColors = [
  'error'      => 'red',
  'warning' => 'yellow',
  'ok'          => 'green'
];
```

And it could be used in a function to get the color like:
```
function getStatusColor(string $status) {
  $labelColors = [
    'error'   => 'red',
    'warning' => 'yellow',
    'ok'      => 'green'
  ];
  
  if (in_array($labelColors, $status, true) === true) {
    return $labelColors[$status]; 
  }

  throw new WhyDoesntPHPHaveEnumsException("Unknown color: $status");
}

getStatusColor($detectedStatus);
```

Which could be written with match as something similar to:

```
function getStatusColor(string $status) {

  return match($status) {
    'error'   => 'red',
    'warning' => 'yellow',
    'ok'      => 'green'
    default: throw new WhyDoesntPHPHaveEnumsException("Unknown color: $status")
  };
}

```

But the first version can be refactored to be more data-driven:

```
function getStatusColor(string $status, array $labelColors) {
  if (in_array($labelColors, $status, true) === true) {
    return $labelColors[$status]; 
  }

  throw new WhyDoesntPHPHaveEnumsException("Unknown color: $status");
}


$labelColors = [
  'error'   => 'red',
  'warning' => 'yellow',
  'ok'      => 'green'
];

getStatusColor($detectedStatus, $labelColors);

```

Something equivalent with match keyword:

```
function getStatusColor(string $status, $labelColors) {

  return match(
    $status,
    $labelColors,
    // Next line is the default
    fn($status) => throw new WhyDoesntPHPHaveEnumsException("Unknown color: $status")
  );
}

$labelColors = [
  'error'   => 'red',
  'warning' => 'yellow',
  'ok'      => 'green'
];

getStatusColor($detectedStatus, $labelColors);

```

Or back to the hard-coded version, but still 

```
function getStatusColor(string $status, $labelColors) {

  $labelColors = [
    'error'   => 'red',
    'warning' => 'yellow',
    'ok'      => 'green'
  ];

  return match(
    $status,
    $labelColors,
    // Next line is the default
    fn($status) => throw new WhyDoesntPHPHaveEnumsException("Unknown color: $status")
  );
}

```

Or inline.
```
function getStatusColor(string $status, $labelColors) {

  $labelColors = ;

  return match(
    $status,
    [
        'error'   => 'red',
        'warning' => 'yellow',
        'ok'      => 'green'
    ],
    // Next line is the default
    fn($status) => throw new WhyDoesntPHPHaveEnumsException("Unknown color: $status")
  );
}
```

Or to summarise that wibbling, couldn't most of the value of match be delivered with just a function?

As functions with 3 bulky parameters are hard to read, there could still be benefit of having a custom syntax for it, but might be worth thinking about other features that overlap with "having special syntax for how lists interact with things" e.g. splat operators, list().

**Comment by iluuu1994** [comment]
Using a map instead of a programming construct has the problems described in the RFC.

```php
$y = [
    1 => ...,
    2 => ...,
][$x];
```

> This code will execute every single “arm”, not just the one that is finally returned. It will also build a hash map in memory every time it is executed. And again, you must not forget to handle unexpected values.

This works fine if you're dealing with constant values but as soon as you try to do any computation in the RHS it won't be feasible (even if you move it to a function as ALL functions will be called).

```php
$y = [
    1 => foo(),
    2 => bar(),
][$x];
// foo() and bar() are called, regardless of $x
```

It also only works for simple values (strings and ints) and that it will do type coercion.

**Comment by Danack** [comment]
Ugh. That kind of comes back to not being able to reference functions directly.

Pretty sure most people coming from Javascript would expect to be able to do:

```
$y = [
    1 => foo,
    2 => bar,
][$x];
```

I've added a brief note on that to [the codex](https://github.com/Danack/RfcCodex/blob/master/referencing_functions.md).

It's a bit like having a jigsaw puzzle where there's too many pieces left to put down...

**Comment by iluuu1994** [comment]
```php
$y = [
    1 => 'foo',
    2 => 'bar',
][$x]();
```

would work, I guess.

**Comment by iluuu1994** [comment]
I don't think there is an equivalent way to write a `match` function as proposed without the drawbacks mentioned above. Thus I'll close this issue.
